Model/urls.py
# Personnel/urls.py
from django.urls import path
from . import views  # Assurez-vous que le fichier views.py existe et contient les vues nécessaires
app_name = 'Model'
urlpatterns = [
]

OGB_BASE/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Personnel.urls'), name='Personnel'),
    path('Utilisateur/', include('Utilisateur.urls'), name='Utilisateur'),
    path('Model/', include('Model.urls'), name='Model'),
    path('', include('pwa.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Utilisateur/urls.py
from django.urls import path
from .views import Connexion, Deconnexion, toggle_dark_mode, gestion_utilisateur, add_user, bloque_user, debloque_user, \
    delete_user, edit_user, reset_password_request, reset_password_validate, reset_password_change, profil, \
    page_blocage, parametre, page_non_trouve

app_name = 'Utilisateur'
urlpatterns = [
    path('', Connexion.as_view(), name='Connexion'),
    path('Deconnexion/', Deconnexion, name='Deconnexion'),
    path('page404/', page_non_trouve, name='page_non_trouve'),
    path('add_user/', add_user, name='add_user'),
    path('parametre/', parametre, name='parametre'),
    path('maintenance/', page_blocage, name='page_blocage'),
    path('profil/', profil, name='profil'),
    path('gestion_utilisateur/', gestion_utilisateur, name='gestion_utilisateur'),
    path('toggle-dark-mode/', toggle_dark_mode, name='toggle_dark_mode'),
    path('bloque_user/<int:user_id>/', bloque_user, name='bloque_user'),
    path('debloque_user/<int:user_id>/', debloque_user, name='debloque_user'),
    path('delete_user/<int:user_id>/', delete_user, name='delete_user'),
    path('edit_user/<int:user_id>/', edit_user, name='edit_user'),
    path('reset-password/', reset_password_request, name='reset_password_request'),
    path('reset-password/validate/', reset_password_validate, name='reset_password_validate'),
    path('reset_password_change/', reset_password_change, name='reset_password_change'),
]

Model/models.py
from django.contrib.auth.base_user import BaseUserManager, AbstractBaseUser
from django.db import models
from datetime import date

from django.db.models import UniqueConstraint

from decimal import Decimal

from django.utils import timezone


class MyUserManager(BaseUserManager):
    def create_user(self, username, password=None, **extra_fields):
        if not username:
            raise ValueError("Vous devez entrer un nom d'utilisateur")

        user = self.model(
            username=username,
            **extra_fields  # Ajout des champs supplémentaires
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, password=None):
        user = self.create_user(username=username, password=password)
        user.is_staff = True
        user.is_superuser = True
        user.save()
        return user

    def create_admin(self, username, email, nom, prenom, roles, password=None):
        if not username:
            raise ValueError("Vous devez entrer un nom d'utilisateur")
        if not email:
            raise ValueError("Vous devez entrer un email")

        user = self.model(
            username=username,
            email=self.normalize_email(email),
            nom=nom,
            prenom=prenom,
            roles=roles
        )
        user.set_password(password)
        user.is_staff = True
        user.is_admin = True
        user.save(using=self._db)
        return user


class Parametre(models.Model):
    info = models.CharField(default="Bienvenue")
    blocage_global = models.BooleanField(default=False, verbose_name="Bloquer l'application")
    titre = models.CharField(default="Information", max_length=100)
    is_afficher = models.BooleanField(default=True)
    image = models.ImageField(upload_to='OGB_Image/', null=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.pk and Parametre.objects.exists():
            raise ValueError("Il ne peut y avoir qu'une seule instance de Parametre.")
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.info} {self.titre}"


class Utilisateur(AbstractBaseUser):
    date_mise_a_jour = models.DateTimeField(verbose_name="Date de mise a jour", auto_now=True)
    username = models.CharField(
        unique=True,
        max_length=255,
        blank=False
    )
    nom = models.CharField(max_length=250, verbose_name='nom')
    prenom = models.CharField(max_length=250)
    email = models.EmailField(max_length=254, null=True, blank=True, verbose_name='Email')
    telephone = models.CharField(max_length=20, null=True, blank=True, verbose_name='Numéro de téléphone')
    last_activity = models.DateTimeField(default=timezone.now)
    is_active = models.BooleanField(default=True)
    dark_mode = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)
    roles = models.CharField(max_length=20, default='EDUCATIF')
    image = models.ImageField(upload_to='ImagesGestionnaire/', null=True, blank=True)
    USERNAME_FIELD = 'username'
    objects = MyUserManager()

    def __str__(self):
        return f"{self.nom} {self.prenom}"

    def est_en_ligne(self):
        if (timezone.now() - self.last_activity).seconds > 60:
            return False
        return True


class Pere_enfant(models.Model):
    nom_pere = models.CharField()
    prenom_pere = models.CharField()
    date_naissance_pere = models.DateField(blank=True, null=True)
    lieu_naissance_pere = models.CharField(blank=True, null=True)
    profession_pere = models.CharField(blank=True, null=True)
    ethnie_pere = models.CharField(blank=True, null=True)
    religion_pere = models.CharField(blank=True, null=True)
    nombre_personne_charge_pere = models.CharField(blank=True, null=True)
    contact_pere = models.CharField(blank=True, null=True)
    adresse_pere = models.CharField(blank=True, null=True)
    en_vie_pere = models.BooleanField(default=True, blank=True, null=True)
    en_couple_pere = models.BooleanField(default=True, blank=True, null=True)


class Mere_enfant(models.Model):
    nom = models.CharField()
    prenom = models.CharField()
    date_naissance = models.DateField(blank=True, null=True)
    lieu_naissance = models.CharField(blank=True, null=True)
    profession = models.CharField(blank=True, null=True)
    ethnie = models.CharField(blank=True, null=True)
    religion = models.CharField(blank=True, null=True)
    nombre_personne_charge = models.CharField(blank=True, null=True)
    contact = models.CharField(blank=True, null=True)
    adresse = models.CharField(blank=True, null=True)
    en_vie = models.BooleanField(default=True, blank=True, null=True)
    en_couple = models.BooleanField(default=True, blank=True, null=True)


class Repondant(models.Model):
    nom = models.CharField()
    prenom = models.CharField()
    nationalite = models.CharField(blank=True, null=True)
    profession = models.CharField(blank=True, null=True)
    ethnie = models.CharField(blank=True, null=True)
    religion = models.CharField(blank=True, null=True)
    contact = models.CharField(blank=True, null=True)
    adresse = models.CharField(blank=True, null=True)
    nombre_piece = models.CharField(blank=True, null=True)
    type_eau = models.CharField(blank=True, null=True)
    electrifie = models.BooleanField(default=True, blank=True, null=True)
    revenu_mensuel = models.BooleanField(default=False, blank=True, null=True)
    en_couple = models.BooleanField(default=True, blank=True, null=True)
    lien_parente = models.CharField(blank=True, null=True)
    type_habitat = models.CharField(blank=True, null=True)


class Pensionnnaire(models.Model):
    type_habitat_enfant = models.CharField(blank=True, null=True)
    personne_loge_enfant = models.CharField(blank=True, null=True)
    lieu_habitation_enfant = models.CharField(blank=True, null=True)
    nombre_piece_logement = models.CharField(blank=True, null=True)
    motif_deplacement_enfant = models.CharField(blank=True, null=True)
    electrifie_enfant = models.BooleanField(default=True, blank=True, null=True)
    nom_enfant = models.CharField()
    prenom_enfant = models.CharField()
    matricule = models.CharField(max_length=15, unique=True)
    date_ouverture_dossier = models.DateField()
    statue = models.CharField(max_length=40, blank=True, null=True)
    date_naissance_enfant = models.DateField()
    lieu_naissance_enfant = models.CharField(blank=True, null=True)
    nationalite_enfant = models.CharField(blank=True, null=True)
    es_scolarise = models.BooleanField(default=True, blank=True, null=True)
    a_antecdents = models.BooleanField(blank=True, null=True)
    niveau_etude_anterieur = models.CharField(blank=True, null=True)
    classe_inscrit = models.CharField(blank=True, null=True)
    religion_enfant = models.CharField(blank=True, null=True)
    taille = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True, verbose_name="Taille (en cm)")
    poids = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True, verbose_name="Poids (en kg)")
    pere = models.ForeignKey(Pere_enfant, on_delete=models.CASCADE, related_name="pensionnaires_pere", null=True,
                             blank=True)
    mere = models.ForeignKey(Mere_enfant, on_delete=models.CASCADE, related_name="pensionnaires_mere", null=True,
                             blank=True)
    repondant = models.ForeignKey(Repondant, on_delete=models.CASCADE, related_name="pensionnaires_repondant",
                                  null=True, blank=True)


class Dossier(models.Model):
    pensionnaire = models.ForeignKey(Pensionnnaire, on_delete=models.CASCADE, related_name="dossiers")
    fichier = models.FileField(upload_to="pensionnaires/dossiers/")
    description = models.CharField(max_length=255, blank=True, null=True)
    date_ajout = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Dossier {self.id} pour {self.pensionnaire.nom_enfant}"


class Classe(models.Model):
    nom_classe = models.CharField(max_length=50)
    annee_scolaire = models.CharField(max_length=9,
                                      default=f"{date.today().year}-{date.today().year + 1}")

    def __str__(self):
        return f"{self.nom_classe} - {self.annee_scolaire}"


class Inscription(models.Model):
    pensionnaire = models.ForeignKey(Pensionnnaire, on_delete=models.CASCADE, related_name="inscriptions")
    classe = models.ForeignKey(Classe, on_delete=models.CASCADE, related_name="inscriptions")
    ecole = models.CharField(blank=True, null=True, default="OGB")
    date_inscription = models.DateField(auto_now_add=True)

    class Meta:
        constraints = [
            UniqueConstraint(fields=['pensionnaire', 'classe'], name='unique_pensionnaire_classe')
        ]

    def __str__(self):
        return f"{self.pensionnaire.nom_enfant} inscrit en {self.classe.nom_classe} ({self.classe.annee_scolaire})"


class Evaluation(models.Model):
    inscription = models.ForeignKey(Inscription, on_delete=models.CASCADE, related_name="evaluations")
    evaluation1 = models.IntegerField(null=True, blank=True)
    evaluation2 = models.IntegerField(null=True, blank=True)
    evaluation3 = models.IntegerField(null=True, blank=True)
    moyenne = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)
    statut_final = models.CharField(max_length=20)

    def save(self, *args, **kwargs):
        if self.moyenne is not None:
            try:
                self.moyenne = Decimal(self.moyenne)
                self.statut_final = 'Admis' if self.moyenne >= 10 else 'Redoublant'
            except (ValueError, TypeError):
                self.statut_final = 'Invalide'

        super().save(*args, **kwargs)

    class Meta:
        constraints = [

Utilisateur/models.py
from django.db import models

# Create your models here.

Utilisateur/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from django.contrib.auth.forms import SetPasswordForm as DjangoSetPasswordForm
from django.contrib.auth.models import User

from Model.models import Utilisateur
from django import forms


class ConnexionForm(AuthenticationForm):

    def __init__(self, *args, **kwargs):
        super(ConnexionForm, self).__init__(*args, **kwargs)
        self.fields['username'].error_messages = {
            'required': "Nom d'utilisateur invalide !"
        }
        self.fields['password'].error_messages = {
            'required': "Mot de passe invalide!"
        }
        self.error_messages.update({
            "invalid_login": "ce compte n'existe pas",
            "inactive": "Ce compte est inactif. Veuillez contacter l'administrateur.",
        })


class UserRegistrationForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(UserRegistrationForm, self).__init__(*args, **kwargs)

        self.fields['username'].error_messages = {
            'unique': 'Ce nom d\'utilisateur existe déjà.',
            'required': 'Ce champ est obligatoire.'
        }

    class Meta:
        model = Utilisateur
        fields = 'username', 'nom', 'prenom'


class UserRegistrationForme(UserCreationForm):
    class Meta:
        model = Utilisateur
        fields = 'username', 'nom', 'prenom', 'roles'

    def __init__(self, *args, **kwargs):
        super(UserRegistrationForme, self).__init__(*args, **kwargs)

        self.fields['username'].error_messages = {
            'unique': 'Ce nom d\'utilisateur existe déjà.',
            'required': 'Ce champ est obligatoire.'
        }


class UserRegistrationFormee(UserChangeForm):
    class Meta:
        model = Utilisateur
        fields = 'nom', 'prenom'


class ResetPasswordRequestForm(forms.Form):
    email = forms.CharField(max_length=255, label="Identifiant (Email ou Téléphone)")


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Utilisateur
        fields = ['username', 'nom', 'prenom', 'email', 'image']


class ProfileImageForm(forms.ModelForm):
    class Meta:
        model = Utilisateur
        fields = ['image']

Utilisateur/templates/profil/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <body class="hold-transition sidebar-mini layout-fixed layout-navbar-fixed sidebar-closed sidebar-collapse layout-navbar-fixed {% if request.user.dark_mode %}dark-mode{% endif %}">
    <div class="wrapper">
        {% include 'preload.html' %}
        {% include 'personnel_navbar.html' %}
        <div class="content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-4 text-center">
                        <div class="profile-img mb-4">
                            {% if user.image %}
                                <img id="imagePreview" src="{{ user.image.url }}" style="border-radius: 50%; width: 100px; height: 100px;" alt="Image de Profil" class="rounded-circle img-fluid border border-primary" />
                            {% else %}
                                <img id="imagePreview" src="" style="border-radius: 50%; width: 100px; height: 100px;" class="rounded-circle img-fluid border border-primary" alt="Prévisualisation" />
                            {% endif %}
                            <div class="mt-2">
                                <form method="POST" action="{% url 'Utilisateur:profil' %}" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    <input type="file" name="image" id="id_image" class="form-control mb-2" accept="image/*" onchange="previewImage(event)" />
                                    <button type="submit" class="btn btn-outline-primary btn-sm">Enregistrer l'image</button>
                                </form>
                            </div>
                        </div>

                    </div>
                    <div class="col-md-8">
                        <h2>{{ user.nom }} {{ user.prenom }}</h2>
                        <p class="text-muted">{{ user.username }}</p>
                    </div>
                </div>
                <div class="card mt-11 shadow-lg">
                    <div class="card-header bg-primary text-white">
                        <h5><i class="fas fa-info-circle"></i> Informations personnelles</h5>
                    </div>
                    <div class="card-body">
                        <form method="POST" x-data="{ editing: false }">
                            {% csrf_token %}
                            <div class="form-row">
                                <div class="col-md-6 mb-3">
                                    <label for="id_prenom">Prénom</label>
                                    <input type="text" value="{{ user.prenom }}" name="prenom" class="form-control" id="id_prenom" :readonly="!editing" />
                                </div>
                                <div class="col-md-6 mb-3">
                                    <label for="id_nom">Nom</label>
                                    <input type="text" name="nom" value="{{ user.nom }}" class="form-control" id="id_nom" :readonly="!editing" />
                                </div>
                                <div class="col-md-6 mb-3">
                                    <label for="id_email">Email</label>
                                    <input type="email" name="email" value="{{ user.email }}" class="form-control" id="id_email" :readonly="!editing" />
                                </div>
                                <div class="col-md-6 mb-3">
                                    <label for="id_username">Nom d'utilisateur</label>
                                    <input type="text" name="username" value="{{ user.username }}" class="form-control" id="id_username" :readonly="!editing" />
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary btn-lg btn-block mt-2" x-show="editing">Sauvegarder les modifications</button>
                        </form>

                    </div>
                </div>
            </div>
        </div>
        <aside class="control-sidebar control-sidebar-dark">
        </aside>
    </div>
    </body>
<style>
body{
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
}
</style>
    <script>
        function previewImage(event) {
            const output = document.getElementById('imagePreview');
            output.src = URL.createObjectURL(event.target.files[0]);
            output.onload = function() {
                URL.revokeObjectURL(output.src)
            }
        }
    </script>

{% endblock %}