Model/urls.py
# Personnel/urls.py
from django.urls import path
from . import views  # Assurez-vous que le fichier views.py existe et contient les vues nécessaires
app_name = 'Model'
urlpatterns = [
]

OGB_BASE/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Personnel.urls'), name='Personnel'),
    path('Utilisateur/', include('Utilisateur.urls'), name='Utilisateur'),
    path('Model/', include('Model.urls'), name='Model'),
    path('', include('pwa.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Personnel/urls.py
# Personnel/urls.py
from django.urls import path
from . import views
from .views import details_pensionnaire, suivi_trimestrielle, create_new_suivi, consultation, create_new_consultation, \
    update_pere_info, update_enfant_info, update_mere_info

app_name = 'Personnel'
urlpatterns = [
    path('', views.acceuil, name='acceuil'),
    path('enregistrer_pensionnaire/', views.enregistrer_pensionnaire, name='enregistrer_pensionnaire'),
    path('espace_scolaire/', views.espace_scolaire, name='espace_scolaire'),
    path('suivi_trimestrielle/', suivi_trimestrielle, name='suivi_trimestrielle'),
    path('ajouter-document/<int:pensionnaire_id>/', views.ajouter_document, name='ajouter_document'),
    path('consultation/', consultation, name='consultation'),
    path('update_pere_info/', update_pere_info, name='update_pere_info'),
    path('update_mere_info/', update_mere_info, name='update_mere_info'),
    path('update_enfant_info/', update_enfant_info, name='update_enfant_info'),
    path('inscription_scolaire/', views.inscription_scolaire, name='inscription_scolaire'),
    path('create_new_suivi/', create_new_suivi, name='create_new_suivi'),
    path('create_new_consultation/', create_new_consultation, name='create_new_consultation'),
    path('rechercher_pensionnaires/', views.rechercher_pensionnaires, name='rechercher_pensionnaires'),
    path('liste_pensionnaire/', views.liste_pensionnaire, name='liste_pensionnaire'),
    path('resultats_scolaire/', views.resultats_scolaire, name='resultats_scolaire'),
    path('detatil_classe/<str:classe>/', views.detatil_classe, name='detatil_classe'),
    path('evaluate/<int:pensionnaire_id>/', views.evaluate_pensionnaire, name='evaluate_pensionnaire'),
    path('enregistrer_pensionnaire_et_pere/', views.enregistrer_pensionnaire_et_pere, name='enregistrer_info'),
    path('details/<int:pensionnaire_id>/', details_pensionnaire, name='details_pensionnaires'),
]

Personnel/models.py
from django.db import models

# Create your models here.

Personnel/views.py
import json
from datetime import datetime, date

from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.db import transaction, IntegrityError
from django.db.models import Count
from django.db.models.functions import Round
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse
from django.db.models import Avg, Count, F
from django.views.decorators.csrf import csrf_exempt

from Model.models import Pensionnnaire, Pere_enfant, Mere_enfant, Inscription, Classe, Evaluation, \
    SuiviMedicalTrimestriele, ConsultationMedicale, Antecedents, Repondant, Dossier
from django.contrib import messages


@login_required(login_url='Utilisateur:Connexion')
def acceuil(request):
    current_date = date.today()
    if current_date.month >= 9:
        annee_scolaire = f"{current_date.year}-{current_date.year + 1}"
    else:
        annee_scolaire = f"{current_date.year - 1}-{current_date.year}"

    today = date.today()
    stats = {
        'total_pensionnaires': Pensionnnaire.objects.count(),
        'consultations_recentes': ConsultationMedicale.objects.filter(annee_scolaire=annee_scolaire,
                                                                      date_consultation__month=today.month).count(),
        'inscriptions_actuelles': Inscription.objects.filter(classe__nom_classe=annee_scolaire).count(),
    }

    total_suivis = SuiviMedicalTrimestriele.objects.filter(annee_scolaire=annee_scolaire).count()
    consultations_data = (
        ConsultationMedicale.objects.filter(date_consultation__month=today.month)
        .values('pensionnaire__nom_enfant')
        .annotate(total=Count('id'))
    )
    data_classe = {
        'labels': [item['pensionnaire__nom_enfant'] for item in consultations_data],
        'values': [item['total'] for item in consultations_data],
    }
    if 'messages' in request.session:
        del request.session['messages']

    return render(
        request,
        'accueil/index.html',
        {
            'stats': stats,
            'total_suivis': total_suivis,
            'data_classe_json': json.dumps(data_classe),
        }
    )


@login_required(login_url='Utilisateur:Connexion')
def enregistrer_pensionnaire(request):
    return render(request, 'enregistrer_pensionnaire/index.html')


@login_required(login_url='Utilisateur:Connexion')
def enregistrer_pensionnaire_et_pere(request):
    if request.method == "POST":
        date_naissance_enfant = request.POST.get('date_naissance_enfant', '').strip()
        date_ouverture_dossier = request.POST.get('date_ouverture_dossier', '').strip()
        nom_enfant = request.POST.get('nom_enfant', '').strip()
        prenom_enfant = request.POST.get('prenom_enfant', '').strip()
        matricule = request.POST.get('matricule', '').strip()
        statue = request.POST.get('statue', '').strip()
        lieu_naissance_enfant = request.POST.get('lieu_naissance_enfant', '').strip()

        nationalite_enfant = request.POST.get('nationalite_enfant', '').strip()
        es_scolarise = request.POST.get('es_scolarise', '').strip()
        a_antecdents = request.POST.get('a_antecdents', '').strip()
        niveau_etude_anterieur = request.POST.get('niveau_etude_anterieur', '').strip()
        classe_inscrit = request.POST.get('classe_inscrit', '').strip()

        religion_enfant = request.POST.get('religion_enfant', '').strip()
        autre_religion_enfant = request.POST.get('autre_religion_enfant', '').strip()
        if religion_enfant == "Autre":
            religion_enfant = autre_religion_enfant
        type_habitat_enfant = request.POST.get('type_habitat_enfant', '').strip()
        personne_loge_enfant = request.POST.get('personne_loge_enfant', '').strip()

        lieu_habitation_enfant = request.POST.get('lieu_habitation_enfant', '').strip()
        autre_lieu_habitation_enfant = request.POST.get('autre_lieu_habitation_enfant', '').strip()
        if lieu_habitation_enfant == "Autre":
            lieu_habitation_enfant = autre_lieu_habitation_enfant

        nombre_piece_logement = request.POST.get('nombre_piece_logement', '').strip()

        motif_deplacement_enfant = request.POST.get('motif_deplacement_enfant', '').strip()
        autre_motif_deplacement_enfant = request.POST.get('autre_motif_deplacement_enfant', '').strip()
        if motif_deplacement_enfant == "Autre":
            motif_deplacement_enfant = autre_motif_deplacement_enfant

        electrifie_enfant = request.POST.get('electrifie_enfant', '').strip()

        nom_pere = request.POST.get('nom_pere', '').strip()
        prenom_pere = request.POST.get('prenom_pere', '').strip()
        date_naissance_pere = request.POST.get('date_naissance_pere', '').strip()
        lieu_naissance_pere = request.POST.get('lieu_naissance_pere', '').strip()
        ethnie_pere = request.POST.get('ethnie_pere', '').strip()

        religion_pere = request.POST.get('religion_pere', '').strip()
        autre_religion_pere = request.POST.get('autre_religion_pere', '').strip()
        if religion_pere == "Autre":
            religion_pere = autre_religion_pere
        nombre_personne_charge_pere = request.POST.get('nombre_personne_charge_pere', '').strip()
        contact_pere = request.POST.get('contact_pere', '').strip()

        adresse_pere = request.POST.get('adresse_pere', '').strip()
        autre_adresse_pere = request.POST.get('autre_adresse_pere', '').strip()
        if adresse_pere == "Autre":
            adresse_pere = autre_adresse_pere

        profession_pere = request.POST.get('profession_pere', '').strip()
        en_vie_pere = request.POST.get('en_vie_pere', '').strip()
        en_couple_pere = request.POST.get('en_couple_pere', '').strip()

        nom_mere = request.POST.get('nom_mere', '').strip()
        nom_repondant = request.POST.get('nom_repondant', '').strip()
        prenom_mere = request.POST.get('prenom_mere', '').strip()
        date_naissance_mere = request.POST.get('date_naissance_mere', '').strip()
        lieu_naissance_mere = request.POST.get('lieu_naissance_mere', '').strip()
        ethnie_mere = request.POST.get('ethnie_mere', '').strip()

        religion_mere = request.POST.get('religion_mere', '').strip()
        autre_religion_mere = request.POST.get('autre_religion_mere', '').strip()
        if religion_mere == "Autre":
            religion_mere = autre_religion_mere
        nombre_personne_charge_mere = request.POST.get('nombre_personne_charge_mere', '').strip()
        contact_mere = request.POST.get('contact_mere', '').strip()

        adresse_mere = request.POST.get('adresse_mere', '').strip()
        autre_adresse_mere = request.POST.get('autre_adresse_mere', '').strip()
        if adresse_mere == "Autre":
            adresse_mere = autre_adresse_mere
        profession_mere = request.POST.get('profession_mere', '').strip()
        en_vie_mere = request.POST.get('en_vie_mere', '').strip()
        en_couple_mere = request.POST.get('en_couple_mere', '').strip()
        en_couple_repondant = request.POST.get('en_couple_repondant', '').strip()
        revenu_mensuel_repondant = request.POST.get('revenu_mensuel_repondant', '').strip()
        electrifie_repondant = request.POST.get('electrifie_repondant', '').strip()

        es_scolarise = True if es_scolarise == "True" else False
        a_antecdents = True if a_antecdents == "True" else False
        en_couple_pere = True if en_couple_pere == "True" else False
        en_couple_mere = True if en_couple_mere == "True" else False
        en_couple_repondant = True if en_couple_repondant == "True" else False
        revenu_mensuel_repondant = True if revenu_mensuel_repondant == "True" else False
        electrifie_repondant = True if electrifie_repondant == "True" else False
        en_vie_mere = True if en_vie_mere == "True" else False
        en_vie_pere = True if en_vie_pere == "True" else False

        if not (nom_enfant and prenom_enfant and matricule and date_naissance_enfant):
            messages.error(request, "Tous les champs obligatoires doivent être remplis.")
            return redirect('Personnel:enregistrer_pensionnaire')

        try:
            date_naissance_enfant = datetime.strptime(date_naissance_enfant, '%Y-%m-%d').date()
            with transaction.atomic():
                mere = None
                pere = None
                repondant = None
                if nom_mere:
                    mere = Mere_enfant.objects.create(
                        prenom=prenom_mere,
                        nom=nom_mere,
                        date_naissance=date_naissance_mere,
                        lieu_naissance=lieu_naissance_mere,
                        ethnie=ethnie_mere,
                        religion=religion_mere,
                        nombre_personne_charge=nombre_personne_charge_mere,
                        contact=contact_mere,
                        adresse=adresse_mere,
                        profession=profession_mere,
                        en_couple=en_couple_mere,
                        en_vie=en_vie_mere,
                    )

                if nom_repondant:
                    repondant = Repondant.objects.create(
                        nom=nom_repondant,
                        prenom=request.POST.get('prenom_repondant', '').strip(),
                        nationalite=request.POST.get('nationalite_repondant', '').strip(),
                        profession=request.POST.get('profession_repondant', '').strip(),
                        ethnie=request.POST.get('ethnie_repondant', '').strip(),
                        religion=request.POST.get('religion_repondant', '').strip(),
                        contact=request.POST.get('contact_repondant', '').strip(),
                        adresse=request.POST.get('adresse_repondant', '').strip(),
                        nombre_piece=request.POST.get('nombre_piece_repondant', '').strip(),

Personnel/templates/accueil/index.html
{% extends 'base.html' %}
{% load static %}
{% load pwa %}
{% progressive_web_app_meta %}

{% block content %}
    <body class="  layout-fixed layout-navbar-fixed   hold-transition sidebar-mini  layout-navbar-fixed sidebar-closed sidebar-collapse {% if request.user.dark_mode %}dark-mode{% endif %}">
    <div class="wrapper">

        {% include 'preload.html' %}

        {% include 'personnel_navbar.html' %}

        <div class="content-wrapper">
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1 class="m-0">ACCUEIL</h1>
                        </div>
                    </div>
                </div>
            </div>
            <section class="content">
                <div class="container-fluid">
                {% if parametre.is_afficher %}
                    <div class="card bg-gradient-info" style="border-radius: 15px; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);">
                        <div class="card-header" style="background: linear-gradient(to right, #00c6ff, #0072ff);">
                            <h3 class="card-title" style="color: white; font-family: 'Arial', sans-serif; font-weight: bold;">
                                <i class="far fa-calendar-alt"></i>
                                {% if parametre %}{{ parametre.titre}}{% endif %}
                            </h3>
                        </div>
                        <div class="card-body" style="font-family: 'Verdana', sans-serif; color: #333;">
                            <p style="font-size: 18px; line-height: 1.5; text-align: justify;">
                                <br>
                                {% if parametre %}{{ parametre.info}}{% endif %}

                            </p>
                        </div>
                    </div>
                    {% else %}

                {% endif %}
                    <div class="row">
                        <div class="col-lg-4 col-6">
                            <div class="small-box bg-info">
                                <div class="inner">
                                    <h3>{{ stats.total_pensionnaires }}</h3>

                                    <p>Pensionnaires</p>
                                </div>
                                <div class="icon">
                                    <i class="ion ion-bag"></i>
                                </div>
                                <a href="{% url 'Personnel:liste_pensionnaire' %}" class="small-box-footer">Plus d'infos <i class="fas fa-arrow-circle-right"></i></a>
                            </div>
                        </div>
                        <div class="col-lg-4 col-6">
                            <div class="small-box bg-success">
                                <div class="inner">
                                    <h3>{{ stats.inscriptions_actuelles|default:"0" }}<sup style="font-size: 20px"></sup></h3>
                                    <p>Inscriptions actuelles</p>
                                </div>
                                <div class="icon">
                                    <i class="ion ion-stats-bars"></i>
                                </div>
                                <a href="{% url 'Personnel:espace_scolaire' %}" class="small-box-footer">Plus d'infos <i class="fas fa-arrow-circle-right"></i></a>
                            </div>
                        </div>
                        <div class="col-lg-4 col-6">
                            <div class="small-box bg-warning">
                                <div class="inner">
                                    <h3>{{ stats.consultations_recentes|default:"0"  }}</h3>

                                    <p>Consultations mensuelles</p>
                                </div>
                                <div class="icon">
                                    <i class="ion ion-person-add"></i>
                                </div>
                                <a href="{% url 'Personnel:consultation' %}" class="small-box-footer">Plus d'infos <i class="fas fa-arrow-circle-right"></i></a>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <section class="col-lg-4 connectedSortable">
                            <div class="card bg-gradient-success">
                                <div class="card-header border-0">

                                    <h3 class="card-title">
                                        <i class="far fa-calendar-alt"></i>
                                        Calendrier
                                    </h3>
                                    <div class="card-tools">
                                        <div class="btn-group">
                                            <button type="button" class="btn btn-success btn-sm dropdown-toggle" data-toggle="dropdown" data-offset="-52">
                                                <i class="fas fa-bars"></i>
                                            </button>
                                            <div class="dropdown-menu" role="menu">
                                                <a href="#" class="dropdown-item">Add new event</a>
                                                <a href="#" class="dropdown-item">Clear events</a>
                                                <div class="dropdown-divider"></div>
                                                <a href="#" class="dropdown-item">View calendar</a>
                                            </div>
                                        </div>
                                        <button type="button" class="btn btn-success btn-sm" data-card-widget="collapse">
                                            <i class="fas fa-minus"></i>
                                        </button>
                                        <button type="button" class="btn btn-success btn-sm" data-card-widget="remove">
                                            <i class="fas fa-times"></i>
                                        </button>
                                    </div>
                                </div>
                                <div class="card-body pt-0">
                                    <div id="calendar" style="width: 100%"></div>
                                </div>
                                <div class="row">
                                    <div class="col-4">
                                        <div id="sparkline-1"></div>
                                    </div>
                                    <div class="col-4 text-center">
                                        <div id="sparkline-2"></div>
                                    </div>
                                    <div class="col-4 text-center">
                                        <div id="sparkline-3"></div>
                                    </div>
                                </div>

                            </div>
                        </section>
                        <div class="col-lg-8">
                            <canvas id="consultationsChart"></canvas>
                        </div>
                    </div>
                </div>
            </section>
        </div>

        <aside class="control-sidebar control-sidebar-dark">
        </aside>
    </div>
    </body>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

    <script>
        // Récupérer le contexte du canvas
        const ctx = document.getElementById('consultationsChart').getContext('2d');

        // Récupérer les données du backend
        const data = {{ data_classe_json|safe }};

        // Initialiser le graphique avec Chart.js
        new Chart(ctx, {
            type: 'bar',
            data: {
                labels: data.labels, // Noms des pensionnaires
                datasets: [{
                    label: 'Consultations du mois actuel',
                    data: data.values, // Nombre de consultations
                    backgroundColor: 'rgba(75, 192, 192, 0.2)',
                    borderColor: 'rgba(75, 192, 192, 1)',
                    borderWidth: 1
                }]
            },
            options: {
                responsive: true,
                scales: {
                    y: {
                        beginAtZero: true
                    }
                }
            }
        });
    </script>
{% endblock %}